- name: 'novel_crawler'
  version: 'v.25.07.07'
  python-file: 'novel_crawler\novel_crawler_v.25.07.07.py'
  install-requirements: [
    'beautifulsoup4',
    'requests',
    'ebooklib',
    'rich'
  ]
  upx: true
  # onefile: 2 # 0:文件夹 1:单文件 2:两者
  icon: 
  windowed: False
  distpath: 'dist'
  output-name: '{{name}}_{{version}}_{{os}}_{{arch}}'

- name: '键盘监听'
  version: 'v.24.07.16'
  python-file: '键盘监听\v.24.07.16.py'
  install-requirements: [
    'keyboard',
    'configparser',
    'pywin32'
  ]
  upx: true
  # onefile: 1
  icon: 
  windowed: False
  distpath: 'dist'
  output-name: '{{name}}_{{version}}_{{os}}_{{arch}}'

- name: '网易云音乐歌单批量下载歌曲'
  version: 'v.24-10-06'
  python-file: '网易云音乐歌单批量下载歌曲\v.24-10-06.py'
  install-requirements: [
    'quote',
    'requests',
    'tabulate',
    'mutagen'
  ]
  upx: true
  # onefile: 1
  icon: 
  windowed: False
  distpath: 'dist'
  output-name: '{{name}}_{{version}}_{{os}}_{{arch}}'

- name: 'ftp_server'
  version: 'v.25-05-02'
  python-file: 'ftp_server\ftp_server_v.25-05-02.py'
  install-requirements: [
    'pyftpdlib'
  ]
  upx: true
  # onefile: 1
  icon: 
  windowed: False
  distpath: 'dist'
  output-name: '{{name}}_{{version}}_{{os}}_{{arch}}'

# - name: 'psql_terminal'
#   version: 
#   os: [
#     'Windows',
#     'Linux'
#   ]
#   python-file: 'psql_terminal\psql_terminal.py'
#   install-requirements: [
#     'psycopg2'
#   ]
#   upx: true
#   icon: 
#   windowed: False
#   distpath: 'dist'
#   output-name: '{{name}}_{{os}}_{{arch}}'

# - name: 'package'
#   version:
#   os: [
#     'Windows',
#     'Linux'
#   ]
#   python-file: 'package\build.py'
#   install-requirements: [
#     'pyinstaller'
#   ]
#   upx: true
#   icon: 
#   windowed: False
#   distpath: 'dist'
#   output-name: '{{name}}_{{version}}_{{os}}_{{arch}}'

- name: 'sunrise_sunset_info'
  version: 'v.25.05.02'
  python-file: 'sunrise_sunset_info\sunrise_sunset_info_v.25.05.02.py'
  install-requirements: [
    'pyftpdlib'
  ]
  upx: true
  # onefile: 1 # 0:文件夹 1:单文件 2:两者
  icon: 
  windowed: False
  distpath: 'dist'
  output-name: '{{name}}_{{version}}_{{os}}_{{arch}}'
