name: Nuitka Package(dev)

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'package/config.yml'

jobs:
  package-and-release:
    runs-on: windows-latest
    
    # 添加必要的权限
    permissions:
      contents: write  # 允许创建发布和上传资源
    
    steps:
    - name: Set Timezone to China Standard Time
      run: tzutil /s "China Standard Time"
      shell: pwsh

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka  pyyaml
    
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Fix Python encoding (Windows)
      run: |
        # 设置Python使用UTF-8编码
        [System.Environment]::SetEnvironmentVariable('PYTHONUTF8', '1', 'Process')
        # 设置控制台编码为UTF-8
        chcp.com 65001

    - name: Run packaging script
      run: |
        cd package
        python nuitka_build.py nuitka_config.yml
        
    - name: Upload files with wildcards
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          ./dist/*.exe
        retention-days: 90
        if-no-files-found: warn
        overwrite: true
