- name: 'novel_crawler'
  version: 'v.25.07.08'
  python-file: 'novel_crawler/novel_crawler_v.25.07.08.py'
  install-requirements: [
    'beautifulsoup4',
    'requests',
    'ebooklib',
    'rich',
    'Pillow'
  ]
  enable-plugins: [
    'upx'
  ]
  # onefile: 2 # 0:文件夹 1:单文件 2:两者
  # distpath: 'dist'
  timeout: 2700
  custom-command: []
  only-linux-command: []
  only-windows-command: []
  clean-cache: # 禁用选定的缓存，设置"all"则为所有缓存。当前允许的值有："all(全部)","ccache","bytecode(字节码)","compression(压缩)","dll-dependencies(dll依赖项)"。
  c-compiler:
    # clang: true # boolean
    # mingw64: # boolean
    lto: # auto(默认),yes,no 启用链接时优化（Link Time Optimization, LTO），减少二进制文件大小并提高性能。
    static-libpython: # auto(默认),yes,no 控制是否静态链接 Python 运行时库。
  windows-specific-controls:
    console-mode: # force（默认,始终启动控制台）,disable(完全禁用控制台),attach(仅使用现有控制台),hide(创建控制台但立即隐藏（后台运行）)
    icon: package/assets/favicon.ico
    uac-admin: # boolean,管理员权限
  output-name-template: '{{name}}_{{version}}_nuitka_{{os}}_{{arch}}{{exe_suffix}}'


- name: 'Keyboard_monitoring'
  version: 'v.24.07.16'
  python-file: '键盘监听/v.24.07.16.py'
  install-requirements: [
    'keyboard',
    'configparser',
    'pywin32',
    'psutil'
  ]
  enable-plugins: [
    'upx'
  ]
  # onefile: 1
  icon: package/assets/favicon.ico 
  windows-disable-console: False
  # distpath: 'dist'
  timeout: 2700
  custom-command: []
  only-linux-command: []
  only-windows-command: []
  clean-cache: # 禁用选定的缓存，设置"all"则为所有缓存。当前允许的值有："all(全部)","ccache","bytecode(字节码)","compression(压缩)","dll-dependencies(dll依赖项)"。
  c-compiler:
    # clang: true # boolean
    # mingw64: # boolean
    lto: # auto(默认),yes,no 启用链接时优化（Link Time Optimization, LTO），减少二进制文件大小并提高性能。
    static-libpython: # auto(默认),yes,no 控制是否静态链接 Python 运行时库。
  windows-specific-controls:
    console-mode: # force（默认,始终启动控制台）,disable(完全禁用控制台),attach(仅使用现有控制台),hide(创建控制台但立即隐藏（后台运行）)
    icon: package/assets/favicon.ico
    uac-admin: # boolean,管理员权限
  output-name-template: '{{name}}_{{version}}_nuitka_{{os}}_{{arch}}{{exe_suffix}}'


- name: 'NetEase_Cloud_Music_Download'
  version: 'v.25-07-08'
  python-file: '网易云音乐歌单批量下载歌曲/v.25-07-08.py'
  install-requirements: [
    'quote',
    'requests',
    'tabulate',
    'mutagen'
  ]
  enable-plugins: [
    'upx'
  ]
  # onefile: 1
  icon: package/assets/favicon.ico 
  windows-disable-console: False
  # distpath: 'dist'
  timeout: 2700
  custom-command: []
  only-linux-command: []
  only-windows-command: []
  clean-cache: # 禁用选定的缓存，设置"all"则为所有缓存。当前允许的值有："all(全部)","ccache","bytecode(字节码)","compression(压缩)","dll-dependencies(dll依赖项)"。
  c-compiler:
    # clang: true # boolean
    # mingw64: # boolean
    lto: # auto(默认),yes,no 启用链接时优化（Link Time Optimization, LTO），减少二进制文件大小并提高性能。
    static-libpython: # auto(默认),yes,no 控制是否静态链接 Python 运行时库。
  windows-specific-controls:
    console-mode: # force（默认,始终启动控制台）,disable(完全禁用控制台),attach(仅使用现有控制台),hide(创建控制台但立即隐藏（后台运行）)
    icon: package/assets/favicon.ico
    uac-admin: # boolean,管理员权限
  output-name-template: '{{name}}_{{version}}_nuitka_{{os}}_{{arch}}{{exe_suffix}}'


- name: 'ftp_server'
  version: 'v.25-05-02'
  python-file: 'ftp_server/ftp_server_v.25-05-02.py'
  install-requirements: [
    'pyftpdlib'
  ]
  enable-plugins: [
    'upx'
  ]
  # onefile: 1
  icon: package/assets/favicon.ico 
  windows-disable-console: False
  # distpath: 'dist'
  timeout: 2700
  custom-command: []
  only-linux-command: []
  only-windows-command: []
  clean-cache: # 禁用选定的缓存，设置"all"则为所有缓存。当前允许的值有："all(全部)","ccache","bytecode(字节码)","compression(压缩)","dll-dependencies(dll依赖项)"。
  c-compiler:
    # clang: true # boolean
    # mingw64: # boolean
    lto: # auto(默认),yes,no 启用链接时优化（Link Time Optimization, LTO），减少二进制文件大小并提高性能。
    static-libpython: # auto(默认),yes,no 控制是否静态链接 Python 运行时库。
  windows-specific-controls:
    console-mode: # force（默认,始终启动控制台）,disable(完全禁用控制台),attach(仅使用现有控制台),hide(创建控制台但立即隐藏（后台运行）)
    icon: package/assets/favicon.ico
    uac-admin: # boolean,管理员权限
  output-name-template: '{{name}}_{{version}}_nuitka_{{os}}_{{arch}}{{exe_suffix}}'


- name: 'sunrise_sunset_info'
  version: 'v.25.05.02'
  python-file: 'sunrise_sunset_info/sunrise_sunset_info_v.25.05.02.py'
  install-requirements: [
    'pyftpdlib',
    'astropy'
  ]
  enable-plugins: [
    'upx'
  ]
  # onefile: 1 # 0:文件夹 1:单文件 2:两者
  icon: package/assets/favicon.ico
  windows-disable-console: False
  # distpath: 'dist'
  timeout: 2700
  custom-command: []
  only-linux-command: []
  only-windows-command: []
  clean-cache: # 禁用选定的缓存，设置"all"则为所有缓存。当前允许的值有："all(全部)","ccache","bytecode(字节码)","compression(压缩)","dll-dependencies(dll依赖项)"。
  c-compiler:
    # clang: true # boolean
    # mingw64: # boolean
    lto: # auto(默认),yes,no 启用链接时优化（Link Time Optimization, LTO），减少二进制文件大小并提高性能。
    static-libpython: # auto(默认),yes,no 控制是否静态链接 Python 运行时库。
  windows-specific-controls:
    console-mode: # force（默认,始终启动控制台）,disable(完全禁用控制台),attach(仅使用现有控制台),hide(创建控制台但立即隐藏（后台运行）)
    icon: package/assets/favicon.ico
    uac-admin: # boolean,管理员权限
  output-name-template: '{{name}}_{{version}}_nuitka_{{os}}_{{arch}}{{exe_suffix}}'

