- name: 'hello_world'
  version: 'v.25.07.08'
  python-file: 'package/hello_world.py'
  install-requirements: [
    'psutil'
  ]
  enable-plugins: [
    'upx'
  ]
  # onefile: 2 # 0:文件夹 1:单文件 2:两者
  icon: package/assets/favicon.ico 
  windows-disable-console: False
  distpath: 'dist'
  timeout: 2700
  output-name-template: '{{name}}_{{version}}_nuitka_{{os}}_{{arch}}'
  custom-command: []
