- name: 'novel_crawler'
  version: 'v.25.07.08'
  python-file: 'novel_crawler\novel_crawler_v.25.07.08.py'
  install-requirements: [
    'beautifulsoup4',
    'requests',
    'ebooklib',
    'rich',
    'Pillow'
  ]
  upx: true
  # onefile: 2 # 0:文件夹 1:单文件 2:两者
  icon: 
  windows-disable-console: False
  distpath: 'dist'
  output-name-template: '{{name}}_{{version}}_nuitka_{{os}}_{{arch}}'
