name: Package and Release EXE Files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install Requirements
      run: |
        for /d %%i in (*) do (
          if exist "%%i/requirements.txt" (
            pip install -r %%i/requirements.txt
          )
        )

    - name: Package Python scripts to EXE
      run: |
        for /d %%i in (*) do (
          set latest_file=
          for %%j in (%%i/*.py) do set latest_file=%%j
          if defined latest_file (
            pyinstaller --onefile --distpath %%i --workpath %%i/build --specpath %%i/spec %%latest_file%%
          )
        )

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.tag_name }}
        release_name: Release ${{ github.event.inputs.release_name }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          for /d %%i in (*) do (
            set latest_file=
            for %%j in (%%i/*.exe) do set latest_file=%%j
            if defined latest_file (
              echo %%latest_file%%
            )
          )
        asset_name: |
          for /d %%i in (*) do (
            set latest_file=
            for %%j in (%%i/*.exe) do set latest_file=%%j
            if defined latest_file (
              echo %%~nlatest_file%%
            )
          )
        asset_content_type: application/octet-stream
