name: Package and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g., v1.0.0)'
        required: true
        type: string
      release_name:
        description: 'Release title'
        required: true
        type: string

jobs:
  package-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: UPX Setup
      run: |
        wget https://github.com/upx/upx/releases/download/v5.0.1/upx-5.0.1-win64.zip
        unzip upx-5.0.1-win64.zip
        mv upx-5.0.1-win64 upx
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyyaml
        
    - name: Run packaging script
      run: |
        cd package
        python build.py config.yml
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: ${{ github.event.inputs.release_name }}
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./package/dist/
        asset_name: ${{ github.event.inputs.tag_name }}-binaries
        asset_content_type: application/octet-stream